### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by Gottox** [knyar/prometheus-remote-backfill#4]
Hi!
We're considering using this tool for a client. As we have some policies regarding open source licensing and couldn't find any notes about the license used could you add a license to this project?

**Comment by knyar** [comment]
Sure, no problem, I've just added a license. I hope you find this code useful, but please keep in mind that this is was created for a one-off task and has not been extensively tested. Good luck!

**Comment by Gottox** [comment]
thank you! :)
