### ISSUE TITLE
Cannot build either of the tools

### ISSUE THREAD

**Issue by mjf** [knyar/prometheus-remote-backfill#5]
Hello,

unable to build either of the tools... Could it be fixed, please?

```
# github.com/knyar/prometheus-remote-backfill/promdump
./promdump.go:93:17: assignment mismatch: 3 variables but api.Query returns 2 values
```

```
# github.com/knyar/prometheus-remote-backfill/promremotewrite
./promremotewrite.go:39:3: cannot use make([]prompb.TimeSeries, 0, 0) (type []prompb.TimeSeries) as type []*prompb.TimeSeries in field value
./promremotewrite.go:53:4: cannot use metricToLabelProtos(s.Metric) (type []prompb.Label) as type []*prompb.Label in field value
./promremotewrite.go:54:4: cannot use samples (type []prompb.Sample) as type []*prompb.Sample in field value
./promremotewrite.go:56:26: cannot use ts (type prompb.TimeSeries) as type *prompb.TimeSeries in append
./promremotewrite.go:61:31: cannot use make([]prompb.TimeSeries, 0, 0) (type []prompb.TimeSeries) as type []*prompb.TimeSeries in field value
```

Thank you.

**Comment by knyar** [comment]
Hi! Thanks for reporting this. I suspect some internal prometheus APIs might have changed in the three years since I originally wrote this. I don't have plans to keep this code up to date, but I will be happy to review your PRs if fixing this is something you would like to do.

**Comment by mjf** [comment]
@knyar Thanks for the response. I'm not sure I'm capable of fixing it (I'm not a programmer at all). This tool is **the only one** I could find (30+ minutes of intensive "googling" and "githubbing") that can use the remote write protocol to write data to anything accepting the protocol. It's definitely very useful then, I think. The common approach of "backfilling" data to Prometheus by manipulating TSDB is completely wrong (because Prometheus does not process them as it would do if the common approach was manipulating WALs instead). Therefor your idea of using the remote write protocol is the right to go, from my point of view (perhaps even better and easier than manipulating WALs or whatever). It's pretty clean. In fact, I need the tools to migrate data **out of Prometheus** I'm trying to get rid of to another system that understands the Prometheus remote write protocol. I'll try the two forks this project has (I just wonder why there are only two forks of it beying potetionally such an useful tool). Thanks. :-)
